Add DenseNet on architectures
semilleroCV/deep-learning-notes pull request #13
Opened 2024-06-28 17:29 UTC by HenryMantilla

### Description

Add fully functional DenseNet model implementation with parameter count verification.

### Checklist
Ensure your pull request meets the following requirements:
- [x] I have reviewed existing notebooks to avoid duplications.
- [x] My notebook is fully executed.
- [x] I have included a list of all libraries and their versions used in the notebook.
- [x] The notebook file is named clearly to reflect the topic _(e.g., `cross-entropy-loss.ipynb`)._
- [x] I have placed the notebook in the appropriate directory under `notebooks/`.
- [x] My code is simple, precise, and adheres to good coding practices.

2024-06-29 13:44 UTC, gpintoruiz requested changes
good notebook!

2024-06-29 13:44 UTC, gpintoruiz commented on README.md
please do not modify the README.md, instead add the information about your notebook in `automation/notebooks-table-data.csv` following the [CONTRIBUTING.md](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md#4-update-the-csv) instructions and the bot will take care of modifying the README.md

2024-06-30 19:33 UTC, HenryMantilla commented on README.md
New commit made, direct modification of README.md removed.

2024-07-01 16:13 UTC, gpintoruiz approved these changes
Good!

2024-07-01 16:14 UTC, merged