Add ViT architecture
semilleroCV/deep-learning-notes pull request #20
Opened 2024-08-08 03:39 UTC by Factral

### Description
This PR adds a python notebook implementing **Vision Transformers (ViT)** architecture https://arxiv.org/pdf/2010.11929  from scratch using PyTorch. 

### Checklist
Ensure your pull request meets the following requirements:
- [ ] I have reviewed existing notebooks to avoid duplications.
- [ ] My notebook is fully executed.
- [ ] I have included a list of all libraries and their versions used in the notebook.
- [ ] The notebook file is named clearly to reflect the topic _(e.g., `cross-entropy-loss.ipynb`)._
- [ ] I have placed the notebook in the appropriate directory under `notebooks/`.
- [ ] My code is simple, precise, and adheres to good coding practices.

2024-08-09 01:29 UTC, gpintoruiz requested changes

2024-08-09 01:29 UTC, gpintoruiz commented on automation/notebooks-table-data.csv
Please write the name of your notebook in [lowercase](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md#3-make-your-changes).

2024-08-09 01:29 UTC, gpintoruiz commented on notebooks/architectures/ViT.ipynb
1. There are some typing errors in your notebook:

![image](https://github.com/user-attachments/assets/59536705-5246-43df-a4f5-ae1c751a0f15)

2. The `datasets` and `transforms` libraries are not being used, I suggest removing them.

2024-08-09 01:35 UTC, Factral commented on automation/notebooks-table-data.csv
solved in [1369e86](https://github.com/semilleroCV/deep-learning-notes/pull/20/commits/1369e86b525d3560e838a60044d9f79936a2b22c)

2024-08-09 01:36 UTC, Factral commented on notebooks/architectures/ViT.ipynb
solved in [1369e86](https://github.com/semilleroCV/deep-learning-notes/pull/20/commits/1369e86b525d3560e838a60044d9f79936a2b22c)

2024-08-09 20:46 UTC, gpintoruiz requested changes

2024-08-09 20:46 UTC, gpintoruiz commented on notebooks/architectures/ViT.ipynb
you also have to change the name of the notebook 😅  (ViT.ipynb -> vit.ipynb)

2024-08-10 01:29 UTC, Factral commented on notebooks/architectures/ViT.ipynb
I had already made the change in the previous commit but it seems that git does not differentiate between lower and upper case when updating a file in a commit. anyways, solved in [199be0f](https://github.com/semilleroCV/deep-learning-notes/pull/20/commits/199be0f39b7472a395b188c35a6a47d6b97d9095)

2024-08-10 21:46 UTC, gpintoruiz reviewed
thanks, great notebook!

2024-08-10 21:47 UTC, merged