Add notebook on ConvMixer implementation
semilleroCV/deep-learning-notes pull request #28
Opened 2024-11-26 05:13 UTC by BrayanQuintero123

### Description
implementation of the "ConvMixer" architecture presented in the paper "Patches Are All You Need?"

### Checklist
Ensure your pull request meets the following requirements:
- [ ] I have reviewed existing notebooks to avoid duplications.
- [ ] My notebook is fully executed.
- [ ] I have included a list of all libraries and their versions used in the notebook.
- [ ] The notebook file is named clearly to reflect the topic _(e.g., `cross-entropy-loss.ipynb`)._
- [ ] I have placed the notebook in the appropriate directory under `notebooks/`.
- [ ] My code is simple, precise, and adheres to good coding practices..

2024-12-17 17:54 UTC, guillepinto requested changes
the notebook name must be completely in lower case, you must also update it in the csv, see [rules](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md#3-make-your-changes)

2024-12-25 15:46 UTC, BrayanQuintero123 commented
changes made in another commit called "change the name of the notebook and the csv name".

2025-01-27 01:06 UTC, guillepinto requested changes
It seems I didn't make myself understood, check the comments again, please

2025-01-27 01:06 UTC, guillepinto commented on automation/notebooks-table-data.csv
Here you can put the name you want to appear in the table, see [rules](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md#4-update-the-csv), it would be ConvMixer, but the name of the notebook, i.e. .ipynb, must be completely in lowercase, see [rules](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md#3-make-your-changes)

2025-01-27 01:06 UTC, guillepinto commented on notebooks/architectures/ConvMixer.ipynb
As I said in the other comment, the name of the .ipynb must be completely lowercase

2025-01-27 04:01 UTC, BrayanQuintero123 commented
changes made in another commit called "Change the Csv name to lowercase".

2025-02-02 22:10 UTC, guillepinto requested changes
The name of the .ipynb FILEE must be completely in lowercase 😭 (ConvMixer.ipynb -> convmixer.ipynb)

2025-02-02 22:10 UTC, guillepinto commented on automation/notebooks-table-data.csv
Nice, now change the name of the .ipynb **FILE**

2025-02-02 23:08 UTC, BrayanQuintero123 commented
changes made in another commit called "only lower case".

2025-02-05 10:31 UTC, jorge1b3 commented
The notebooks table data file has made changes that now make conflicts with the changes that you proposed. Please fix it.

2025-02-05 19:41 UTC, BrayanQuintero123 commented
changes made in another commit called "conflicts resolved with main".

2025-02-06 00:26 UTC, guillepinto approved these changes
LGTM

2025-02-06 00:26 UTC, merged